FROM nginx:alpine

# Nettoyage total
RUN rm -rf /usr/share/nginx/html/*

# On s'assure que Nginx a les droits sur le dossier
RUN mkdir -p /usr/share/nginx/html

# Copie spécifique : on cible le dossier frontend
COPY . /usr/share/nginx/html/

# Correction des permissions pour éviter le 403
RUN chmod -R 755 /usr/share/nginx/html && \
    chown -R nginx:nginx /usr/share/nginx/html

# Vérifie bien que le fichier s'appelle ngnix.conf (avec l'erreur d'orthographe si elle existe sur ton PC)
COPY ngnix.conf /etc/nginx/conf.d/default.conf

EXPOSE 80